# roles/database/tasks/main.yml
---
- name: 1. Install MariaDB server package
  apt: name=mariadb-server state=present

- name: 2. Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install python Mysql package #required for mysql_db tasks
  apt: name=python3-mysqldb state=latest

- name: 3. Create a new database
  mysql_db: name=demo state=present collation=utf8_general_ci

- name: 4. Create a database user
  mysql_user: 
    name: demo 
    password: demo 
    priv: '*.*:ALL'
    host: localhost 
    state: present

- name: 5a. Copy sample data
  copy: src=dump.sql dest=/tmp/dump.sql
  
- name: 5b. Insert sample data
  shell: cat /tmp/dump.sql | mysql -u demo -pdemo demo

- name: 6. Restart Apache
  service: name=apache2 state=restarted

- name: 7. Install Hello World PHP script with database
  copy: src=db.php dest=/var/www/html/db.php mode=0664